global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']  # Usa el puerto del exporter

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']  # Si instrumentas metrics

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8001']  # Si instrumentas metrics

